### ISSUE TITLE
When the code is open? :)

### ISSUE THREAD

**Issue by SteveTanggithub** [HW-AARC-CLUB/ICASSP_SER#1]

**Comment by hemarathore** [comment]
which paper?

**Comment by SteveTanggithub** [comment]
2021 ICASSP PAPER A NOVEL END-TO-END SPEECH EMOTION RECOGNITION NETWORK WITH STACKED
TRANSFORMER LAYERS

**Comment by hemarathore** [comment]
@SteveTanggithub Thanks
I dont think the author will reply, near future , This huge improvement in accuracy is not that easy.
Accuracy on this dataset for audio only is 66% on whole 5531 utterances for 4 emotion classes. Anybody who is claiming for more should provide the code. otherwise its difficult to verify.

**Comment by wsstriving** [comment]
> @SteveTanggithub Thanks I dont think the author will reply, near future , This huge improvement in accuracy is not that easy. Accuracy on this dataset for audio only is 66% on whole 5531 utterances for 4 emotion classes. Anybody who is claiming for more should provide the code. otherwise its difficult to verify.

To be honest, I don't believe the claim in this paper, the author should prove this unusual improvement or withdraw this paper.

**Comment by zeroRoman** [comment]
Please read our ReadMe

**Comment by tidess** [comment]
> Please read our ReadMe

multi_branch is what ? where is code...

**Comment by zxpoqas123** [comment]
Looking forward to your open source code... To be honest, I don't believe such a high performance simply by introducing the STLs.  
I noticed that you have provided the data split code. But you should probably provide the **EXACT** csv files that contain train, valid and test data, respectively, to guarantee the reproduction. 
It's normal that inclusive speaker experiments can derive higher performance, but it's pretty exaggerated to obtain over 90% of UA and WA, simply using the acoustic information.

**Comment by zeroRoman** [comment]
> Looking forward to your open source code... To be honest, I don't believe such a high performance simply by introducing the STLs. I noticed that you have provided the data split code. But you should probably provide the **EXACT** csv files that contain train, valid and test data, respectively, to guarantee the reproduction. It's normal that inclusive speaker experiments can derive higher performance, but it's pretty exaggerated to obtain over 90% of UA and WA, simply using the acoustic information.

Thank you for your query and we will update the rest of the code as soon as possible.

**Comment by zeroRoman** [comment]
> > Looking forward to your open source code... To be honest, I don't believe such a high performance simply by introducing the STLs. I noticed that you have provided the data split code. But you should probably provide the **EXACT** csv files that contain train, valid and test data, respectively, to guarantee the reproduction. It's normal that inclusive speaker experiments can derive higher performance, but it's pretty exaggerated to obtain over 90% of UA and WA, simply using the acoustic information.
> 
> Thank you for your query and we will update the rest of the code as soon as possible.
